name: xeus-nelson
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Host dependencies
  - xeus-zmq >=1.3.0,<2.0
  - nlohmann_json
  - cppzmq
  - xtl
  - nelson-core >=0.3,<0.4
  # Test dependencies
  - pytest
  - jupyter_kernel_test>=0.4.3
  - nbval
  - pytest-rerunfailures
