name: xeus-nelson-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nelson >=0.3,<0.4
  - nlohmann_json
  - xeus-lite
  - xeus >=3.2.0,<4.0
  - xtl >=0.7,<0.8
